#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#

easy_admin:
  entities:
    User:
      class: App\Entity\Users
      list:
        title: 'Users'
        fields:
          - id
          - email
          - name
          - lastName
          - time

  site_name: 'ExChange'
  design:
      menu:
        - { entity: 'User', icon: 'user' }