<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90Yjdoy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90Yjdoy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container90Yjdoy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container90Yjdoy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container90Yjdoy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '90Yjdoy',
    'container.build_id' => '5e5fa392',
    'container.build_time' => 1550850416,
], __DIR__.\DIRECTORY_SEPARATOR.'Container90Yjdoy');
